apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: resume-builder
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ModiniPadmaSree/argo-app.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: resume
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
